### ISSUE TITLE
Can't build on MINGW64

### ISSUE THREAD

**Issue by tuxymuxy** [FDH2/UxPlay#320] opened 2024-08-05 06:39 UTC
![image](https://github.com/user-attachments/assets/1738bc60-2cb6-4d6b-8013-ea80ccfe447e)

i cloned the repo, installed requirements, but i get this error when i try to build it:
ninja: error: loading 'build.ninja': The system cannot find the specified file.

`cmake ..` just returns nothing

**Comment by fduncanh** [comment] 2024-08-05 23:19
> cmake .. just returns nothing?????

you must be  doing something wrong.

* read the instructions again
*  cmake .. should give you some output, even if only an error message.

what do
* ls -l
* ls -l ..
* which cmake
* cmake --version

report?

**Comment by tuxymuxy** [comment] 2024-08-06 07:54
i think my cmake is bugged or i dont know, but `cmake --version doesnt show anything`
![image](https://github.com/user-attachments/assets/784c2339-dc81-41d0-ae91-2f3bf20e2292)

**Comment by tuxymuxy** [comment] 2024-08-07 14:05
still does the same. i think i give up :(

**Comment by fduncanh** [comment] 2024-08-07 15:16
cmake --version      (on windows10)
reports
```
$ cmake --version
cmake version 3.30.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).


```

no idea why your cmake isnt working ???


run "cmake --version" again   (NOT "cmake  -version .."  which does not produce any output)

"cmake " by itself should produce
```
$ cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.



```
maybe delete /mingw64/bin.cmake  , do "which cmake" again to verify  its gone, and  reinstall it

**Comment by fduncanh** [comment] 2024-08-09 22:56
Not a UxPlay issue,  but a strange  "cmake issue on Windows/mingw64" which we could not reproduce.

closing, but please let us know if you solve the issue.

**Closed** 2024-08-10 16:10 UTC
