### ISSUE TITLE
AlpineLinux uxplay video hickup.

### ISSUE THREAD

**Issue by wenerme** [FDH2/UxPlay#266] opened 2024-01-16 08:41 UTC
I use alpine on amd64 as host. uxplay works like stop a will then works again.

https://github.com/FDH2/UxPlay/assets/1777211/86e3b1c5-8478-48b3-b198-ae745e87b769

When hickups happens, the cpu will be lower.

![image](https://github.com/FDH2/UxPlay/assets/1777211/caca8d1f-f06d-4eda-afaa-62aaf451de6a)

I tried using lan instead wifi, the problem still exists.

Sometimes the video quality will be lower, but not hickups, when hickups, the video quality is quite high.

```
OS: Alpine Linux v3.19 x86_64
Kernel: 6.6.9-0-lts
Uptime: 1 day, 23 hours, 28 mins
Packages: 125 (apk)
Shell: bash 5.2.21
Terminal: /dev/pts/0
CPU: Intel Pentium 4405U (4) @ 2.100GHz
Memory: 102MiB / 15923MiB
```

xref https://github.com/FDH2/UxPlay/issues/264#issuecomment-1888437952

**Comment by wenerme** [comment] 2024-01-16 09:52
Tried glimagesink, same problem, but full cpu load

![image](https://github.com/FDH2/UxPlay/assets/1777211/85f9add6-79ab-47c4-b35d-e07ddb83c51c)

**Comment by fduncanh** [comment] 2024-01-18 20:54
we now have an alpine 1.39 "SYS" test installation on x86_64 (Intel i7) with KDE plasma

Only weirdness is  that in an X11 (as opposed to Wayland) session,  "uxplay" or "uxplay -vs xvimagesink" causes an error that terminates the user session and restarts sddm.  see #259  
Seems that alpine +  GStreamer's xvimagesink don't work together under X11.   Not sure how to debug this.
```
var/log/messages shows:

Jan 18 15:20:05 [host] user.notice libddcutil[3617]: libddcutil terminating.
Jan 18 15:20:05 [host] user.err pulseaudio[3700]: [pulseaudio] stdin-util.c: Lost I/O connection in module "module-gsettings"
Jan 18 15:20:05 [host] authpriv.info : pam_unix(sddm:session): session closed for user 
```


*We cannot reproduce your video "hickups", maybe a network issue.

**Comment by wenerme** [comment] 2024-01-19 07:33
Thanks, I will add more logs about the hickups, I tried cable network, same problem.

I found the same problem about the `uxplay -vs xvimagesink` trigger relogin, but ximagesink works fine, I don't know how to use wayland yet.

**Comment by fduncanh** [comment] 2024-01-19 20:30
If you wish to report the xvimagesink problem to the alpine linux bugs reporting system, it can be simply demonstrated by


```
 gst-launch-1.0 videotestsrc ! videoconvert ! xvimagesink
```

(works fine with xvimagesink -> ximagesink)

Note that this is seen when running KDE Plasma 5.27 in X11 on alpine 1.39  on X86_64 GStreamer 1.22.8

**Comment by fduncanh** [comment] 2024-01-25 19:57
Closing for now (cannot reproduce).
Fell free to reopen, or open a new issue.

**Closed by fduncanh** 2024-01-25 19:57 UTC
