### ISSUE TITLE
video renderer paused when AirPlay streaming video / screen orientation changed

### ISSUE THREAD

**Issue by DYY-Studio** [FDH2/UxPlay#346] opened 2024-09-19 20:00 UTC
### Situation 1: Stream video via AirPlay
Device: **iPhone SE 3rd Gen, iOS 16.3**; **iPad Pro 11-inch 2022, iOS 18.0**
Version: **h265_new** 0473ccd

options: **NONE** / **-h265**

* Connect to UxPlay
* Open system Album App / Other App that support video stream through AirPlay
* Play a video

At the same time, audio is normally streaming.

The master 0a2dbaa can successfully receive the video stream and play, without any options.

The debug logging has been redirected to the log file.
[test.log](https://github.com/user-attachments/files/17066172/test.log)

### Situation 2: Change screen orientation.
Device: **iPhone SE 3rd Gen, iOS 16.3**
Version: **h265_new** 0473ccd

options: **NONE**

* Connect to UxPlay
* Open a App that need change screen orientation

Same with situation 1, master branch works properly.

The debug logging has been redirected to the log file.
[test3.log](https://github.com/user-attachments/files/17066269/test3.log)

**Comment by fduncanh** [comment] 2024-09-20 15:08
In uxplay.cpp h265_new line 1372: features bit 9 "supports screen rotation" is turned off.  This was done in uxplay's ancestor "rpiplay".   what happens when this bit is set to "on"?

**Comment by DYY-Studio** [comment] 2024-09-20 15:45
Sorry I may not test the situation 2 and write wrong information, but the situation 1 do not need rotation.

**Comment by DYY-Studio** [comment] 2024-09-20 19:11
I just means that the **h265_new** works differently compared to the **master**.

So the **master** has same value, but still accepts rotation…?

I personally think that, let it works just like **master** branch is not bad. The **master** branch do not have big issue when deal with these two situation as far as I know.

**These are just my personal idea.** If do not have the plan to support, that's fine, and we can close this issue?

**Comment by fduncanh** [comment] 2024-09-21 06:41
the h265_new branch is still in testing phase.

Your reports are useful.

It wont be released to replace master branch (add h265 support to master branch), until it works properly.

**Comment by fduncanh** [comment] 2024-09-28 23:42
@DYY-Studio 

We have reproduced this:  uxplay-1.69 works fine,  h265_new freezes video when the ipad is rotated.
This is without the -h265 option so it is an unexpected reversion, as h265_new without -h265 *should* work identically as
uxplay-1.69, by clearly does not.   

* will investigate: thanks for this report.

**Comment by fduncanh** [comment] 2024-09-28 23:54
OK this happens (without the -h265 option)  in h265_new  when features bit 42   ("Supports Screen Multi Codec") is set to "on".

* **Since setting this bit is needed to get h265 video working, we hill have to see if we can fix this somehow....**

Will try to find the solution, this is quite annoying!

**Comment by fduncanh** [comment] 2024-09-29 00:50
@DYY-Studio 

Its not that bad: switching bit 42 on in uxplay-1.69 does NOT break video rotation.

(though switching it off fixes it in h265_new!)

So there is interaction  with some other change in  h265_new, so it should be fixable!

**Comment by fduncanh** [comment] 2024-09-29 02:48
I have an idea where this is coming from now.   When video rotates,  new video format info (SPS+PPS)  gets sent, and h265_new modifies how this is handled, so error is probably there

**Comment by fduncanh** [comment] 2024-09-29 03:54
error is elated to #209


currently in h265_new, video in gstreamer-1.24.0 and later is paused when  the video orientation change happens, and never get resumed. will work out a fix

**Comment by fduncanh** [comment] 2024-09-29 04:25
I think this is fixed now.
 
closing, and thank you @DYY-Studio  for your valuable reports  (including your original report that stimulated our work on h265!)
Please reopen if the fix is not working,  (or report any new issues you find)

**Closed by fduncanh** 2024-09-29 04:25 UTC
