### ISSUE TITLE
Fullscreen shows top window bar on first start

### ISSUE THREAD

**Issue by Trekky12** [FDH2/UxPlay#365] opened 2024-11-27 19:42 UTC
When using the fullscreen mode (`uxplay -fs`) with the auto videosink (using "glimagesink") on the first connection the top window bar is still shown. On subsequent connections the fullscreen is correct.

Does anybody has any idea how to fix this?

**Comment by fduncanh** [comment] 2024-11-29 01:26
AFAIK  glimagesink doesnt support full screen mode as an option.   can you give full details?  (which uxplay version, which operating system/ platform,  what kind of video (X11, wayland etc)?)

* how do you know autovideosink selected glimagesink?   uxplay -d  (in uxplay-1.70 or later) will tell you what videosink got selected by autovideosink.

https://gstreamer.freedesktop.org/documentation/opengl/glimagesink.html?gi-language=c

**Comment by Trekky12** [comment] 2024-11-29 04:57
I build unplay from the master branch yesterday. My OS is Ubuntu 24.04.1 which uses Wayland.
The selected sink was found in the debug log (-d) like you described.

Actually fullscreen is working as expected AFTER the first connection after boot. Even when uxplay is stopped and started later fullscreen is working as expected. Only on the very first start after boot with the first connection the title bar is shown. When the connection is stopped and started another time the title bar is shown for a millisecond and then the window is going to fullscreen as expected.

**Comment by fduncanh** [comment] 2024-11-30 08:00
* checked with ubuntu-24.04.1 with wayland.
* the audtovideosink picked xvimagesink not glimagesink.
Can you post your uxplay  -d (debug) output showing that on your system you really get glimagesink.  ( On our test system -vs glimagesink is not working correctly with wayland)


* yes, -fs with wayland  and xvimagesink, I saw that uxplay doesn't give a full screen initially, but does if the connection is closed and reopened.   will  investigate.

**Comment by fduncanh** [comment] 2024-11-30 08:28
* The issue is not very reproducible here.  saw it once, but not after that, even after shutting down  ubuntu and restarting.   

try using "uxplay -vs xvimagesink -fs"  do you see the issue with that?

You can deselect wayland by clicking on the tiny cogwheel in lower right corner of screen before entering your log-in password.    Do you still see your issue without wayland?

**Comment by Trekky12** [comment] 2024-11-30 09:56
Thank you for your investiation. 

I was more than sure that "glimagesink" was selected but when I run `uxplay -d` there is indeed "xvimagesink" automatically selected. Sorry for this confusion.

It seems when the first action after booting (and login) is starting uxplay -fs the title bar is most of the time still visible, afterwards the time the title bar is shown for a millisecond and the screen switches to fullscreen.
This event occurs when not using wayland but x11 and event when xvimagesink is set.

Interesting that you only saw it once.

**Comment by fduncanh** [comment] 2024-12-01 06:41
>Actually fullscreen is working as expected AFTER the first connection after boot. 

So you are reporting  the very first time you lunch uxplay  **AFTER BOOTING THE COMPUTER** is the only time you see this?

I saw it again one time. (first launch of uxplay) .  and only in ubuntu-24.4 not 22.4 or 20.4, or arch and other linuxes. but didn't understand that you reported it as only occurring once after booting.

Does in matter if you launch some other applications after booting, and then launch uxplay?

**Comment by fduncanh** [comment] 2024-12-07 06:43
@Trekky12 : we can't reliably reproduce your issue (though have seen it occasionally)



* If you run "gst-inspect-1.0" before running uxplay, does this prevent the issue from happening?

**Comment by Trekky12** [comment] 2024-12-07 16:15
Thank you for your effort. Unfortunately running "gst-inspect-1.0" before running uxplay -fs doesn't prevent this.

Actually it is no big problem since the title bar is not visible on the second connect so as workaround it is possible to connect, then disconnect and connect a second time to have the title bar invisible.

I can reproduct it on each boot and can make more tests but if this is not reproducable for you, you can also close this issue. I can live with the workaround ;-)

**Comment by fduncanh** [comment] 2024-12-08 15:41
It's a mystery:  if it really doesnt matter how long after boot the first call to uxplay which exhibits this happens,  surely its something to do with initialization of gstreamer. ???       Thats why I thought that running  gst-inspect-1.0 first might do something.


running as

```
export GST_DEBUG=4
uxplay -d -fs > debug_fs1.txt 2>&1
```
 then
```
uxplay -d -fs > debug_fs2.txt 2>&1
```
will produce extensive data from GStreamer's debug facility that may help see what is happening, t o see what is happening differently

**Comment by Trekky12** [comment] 2024-12-08 18:37
Sure thing I created the corresponding debug files:
debug_fs1.txt: https://pastebin.com/AW1bswrs
debug_fs2.txt: https://pastebin.com/ZrxfR0if

**Comment by fduncanh** [comment] 2024-12-09 17:03
Thanks. 
I already see it's not a GStreamer issue.   In your debug trace, autovideosink selecs xvimagesink, which uses X11 (XWindows) to handle fullscreen mode.

at line 349 in renderers/video_renderer.c:
```
if (renderer->gst_window->window) {
                logger_log(logger, LOGGER_INFO, "\n*** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode\n");
                if (fullscreen) {
                    set_fullscreen(renderer->gst_window, &fullscreen);
                }
            }
```
You get there, we see the LOGGER_INFO message.
We need to check that the boolean variable "fullscreen" is in fact "true":   If it is, will need to see what set_fullscreen is doing or not doing.

please add a line to code as below, and report what it shows when you get the issue and when you don't  thanks
```
if (renderer->gst_window->window) {
                logger_log(logger, LOGGER_INFO, "\n*** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode\n");
               printf("fullscreen is set to %s\n", (fullscreen ? "true" : "false"));
                if (fullscreen) {
                    set_fullscreen(renderer->gst_window, &fullscreen);
                }
            }
```

**Comment by Trekky12** [comment] 2024-12-09 17:41
I think this is not the problem, because either way fullscreen is set to true: on the initial run after boot (with title bar) and on subsequent runs (without title bar).

**Comment by fduncanh** [comment] 2024-12-09 20:29
Good.   That js what I expected.

The issue must be a failure in x_display_fix.h.   Some fragility or race condition.       stay tuned.

**Comment by fduncanh** [comment] 2024-12-09 20:43
Here is set_fullscreen:

```
void set_fullscreen(X11_Window_t * X11, bool * fullscreen) {
    XClientMessageEvent msg = {
        .type = ClientMessage,
        .display = X11->display,
        .window = X11->window,
        .message_type = XInternAtom(X11->display, "_NET_WM_STATE", True),
        .format = 32,
        .data = { .l = {
                *fullscreen,
                XInternAtom(X11->display, "_NET_WM_STATE_FULLSCREEN", True),
                None,
                0,
                1
            }}
    };
    XSendEvent(X11->display, XRootWindow(X11->display, XDefaultScreen(X11->display)),
               False, SubstructureRedirectMask | SubstructureNotifyMask, (XEvent*) &msg);
    XSync(X11->display, False);
}
```
* probably need to test if XSendEvent or XSync have any useful return codes.   and if X11->display and  X11-window are correctly set.    



This is the initial use:
```
            if (renderer->gst_window->window) {
                logger_log(logger, LOGGER_INFO, "\n*** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode\n");
                if (fullscreen) {
                    set_fullscreen(renderer->gst_window, &fullscreen);
                }
            }
```

This is the use of set_fullscreen later, to switch fullscreen on and off when the alt-enter key combination is toggled: 
```
                                fullscreen = !(fullscreen);
                                set_fullscreen(renderer_type[type]->gst_window, &fullscreen);

```

**Comment by fduncanh** [comment] 2024-12-09 20:54
let's check  that "display" is known.    Add the g_assert line shown below:

```
#ifdef X_DISPLAY_FIX
        if (renderer->gst_window && !(renderer->gst_window->window) && renderer->use_x11) {
            X11_search_attempts++;
            logger_log(logger, LOGGER_DEBUG, "Looking for X11 UxPlay Window, attempt %d", (int) X11_search_attempts);
            get_x_window(renderer->gst_window, renderer->server_name);
            if (renderer->gst_window->window) {
                logger_log(logger, LOGGER_INFO, "\n*** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode\n");
                if (fullscreen) {
                    g_assert(renderer->gst_window->display);      <========ADDED LINE.
                    set_fullscreen(renderer->gst_window, &fullscreen);
                }
            }
        }
#endif
```

**Comment by fduncanh** [comment] 2024-12-09 21:04
https://www.x.org/releases/X11R7.5/doc/man/man3/XSendEvent.3.html

>XSendEvent returns zero if the conversion to wire protocol format failed and returns nonzero otherwise. XSendEvent can generate BadValue and BadWindow errors. 

In set_fullscreen, test for XSendEvent errors:

if (!XSendEvent(.....) ) {
    printf("XSendEvent failure");
}

**Comment by fduncanh** [comment] 2024-12-09 21:11
https://tronche.com/gui/x/xlib/event-handling/protocol-errors/default-handlers.html

**Comment by fduncanh** [comment] 2024-12-09 23:05
* it seems clear this is an X11 (or X11 emulated by wayland)  issue.   presumably both, as you say it happens if "ubuntu" rather that "ubuntun on wayland" is chosen

* I would guess it is not the first time after boot that matters, but the first time after the window manager starts.

* to  test this ,  get a console with ctrl-Alt-F3, login and do 

"
sudo telinit 3
sudo telinit 5
```
this will stop and restart the window manager.

use this to see if the issue is connected to first run after booting or to first run after starting the window manager.

**Comment by Trekky12** [comment] 2024-12-10 18:22
I've tested all your suggestions:
* apparently the display is known since gassert is not throwing an exception
* XSendEvent is not false
* Restarting the window manager indeed seems to re-trigger the error
  * telinit was not working all the time since my display makes some problems but sometimes it worked and when the window manager is correctly restarted the error was also triggered
  * restarting the window manager with `sudo systemctl restart gdm` was working always and the error was always triggerd

So yes, apparently the error occurs on the first run after starting the window manager...

**Comment by fduncanh** [comment] 2024-12-12 05:29
* so (1) it  occurs only the first time aftre the window manager starts (2) it is nothing to do with gstreamer  (3) It involves the X11 code but also happens with Wayland. (4) it's not easily reproducible , except on @Trekky12 's system, but has occasionally be seen on our Ubunutu 24-04.1 test system.

* maybe some race condition???  (in the window system?)    One thing to try, repeat the "set_fullscreen" call in 
 video-renderer.c  (now at line 466 in uxplay-1.71  - newly posted  at github)

```
#ifdef X_DISPLAY_FIX
        if (renderer->gst_window && !(renderer->gst_window->window) && renderer->use_x11) {
            X11_search_attempts++;
            logger_log(logger, LOGGER_DEBUG, "Looking for X11 UxPlay Window, attempt %d", (int) X11_search_attempts);
            get_x_window(renderer->gst_window, renderer->server_name);
            if (renderer->gst_window->window) {
                logger_log(logger, LOGGER_INFO, "\n*** X11 Windows: Use key F11 or (left Alt)+Enter to toggle full-screen mode\n");
                    set_fullscreen(renderer->gst_window, &fullscreen);
                    set_fullscreen(renderer->gst_window, &fullscreen);  <=========== added line
                }
            }
        }
#endif
```

* otherwise, have you tried  "uxplay -fs -vs waylandsink"  ?

**Comment by Trekky12** [comment] 2024-12-13 18:58
A race condition is indeed a possibility. Adding another call so set_fullscreen does unfortunately not solve this.

waylandsink is not working with the following error:
```
(uxplay:11233): GStreamer-Wayland-CRITICAL **: 19:56:23.457: gst_wl_window_ensure_fullscreen: assertion 'self' failed
*** ERROR: Failed to initialize GStreamer video renderer 1
```

**Comment by fduncanh** [comment] 2024-12-13 21:23
Just to be clear.

1.    always give the exact calling line e.g "uxplay -vs waylandisink " used?  any "display" options added etc.
2.  Is this ubuntu 24.04.1 on raspberry pi ?   is  the display is attached to the PI or somewhere else on X11?

**Comment by fduncanh** [comment] 2024-12-13 21:44
>waylandsink is not working with the following error:

>(uxplay:11233): GStreamer-Wayland-CRITICAL **: 19:56:23.457: gst_wl_window_ensure_fullscreen: assertion 'self' failed
*** ERROR: Failed to initialize GStreamer video renderer 1

I got this error message for GStreamer too, when uxplay starts, 

```
uxplay -vs waylandsink -fs 
```

but when the client makes the connection, full screen is working fine on waylandsink, so just ignore this error message from GStreamer.

**Comment by fduncanh** [comment] 2024-12-13 22:09
Have eliminated the "***ERROR: Failed" which is a UxPlay message:   it was not true that video renderer 1 failed to initialize, by its status was being checked without out a timeout: using a time confiormed it in itializes properlky even thou there is a GStreamer-Wayland error message

*Now fixed in github master branch

Does "uxplay -vs waylandsink -fs" work for you?

**Comment by Trekky12** [comment] 2024-12-14 11:42
> * this is Ubuntu 24.04.1 on an x86_64 desktop, correct?

yes this is correct.

> Does "uxplay -vs waylandsink -fs" work for you?

Yes this is working 🥳 Sorry for not testing it propertly at the beginning. I was testing various videosinks but no futher than the error message. I assumed it is not working with the error -.-

**Comment by fduncanh** [comment] 2024-12-14 15:18
The misleading ***ERROR message will no longer appear if you use latest github master branch code.

* your original issue is still a mystery, but since it's not easily reproducible and uxplay is working for you with -vs waylandsink, we'll close this issue.

* Thanks for the report!

**Closed by fduncanh** 2024-12-14 15:18 UTC
