### ISSUE TITLE
Fixed: UxPlay on Windows now correctly closes connections if the network connection is lost(was: Stream doesn't drop on network change)

### ISSUE THREAD

**Issue by ank-007** [FDH2/UxPlay#367] opened 2024-12-03 06:09 UTC
the issue is simple, if sender changes the network while connected  and sharing his screen to uxplay receiver, uxplay gets stuck in the last frame it got and doesn't drop ( it should drop like it does for disconnecting after getting error ideally).

receiver is running on my mini pc ( win 11)
sender is my iphone 14 with ios 18

uxplay was ran with the command  "uxplay -n name -nh vsync no -d"

I checked debug logs, after changing the network, I get the error after some time saying 
"ERROR: raop_rtp_mirror error in header recv: 0 No error
raop_rtp_mirror exiting TCP thread"

**Comment by ank-007** [comment] 2024-12-04 03:47
in my sender, if the wifi changes automatically ( let's say if it switches from wifi1, which is what receiver also connected to -----> to wifi2 which my phone detected as better connection than the wifi1)

**Comment by fduncanh** [comment] 2024-12-05 00:04
>I checked debug logs, after changing the network, I get the error after some time saying
"ERROR: raop_rtp_mirror error in header recv: 0 No error
raop_rtp_mirror exiting TCP thread
:

**I'm confused by the fact that errno = 0 "no error"

may just add a line

can you test this?
```
          } else if (payload == NULL && ret == -1) {
               if (errno == 0) continue;              <===== ADD THIS AFTER LINE 303
```

relevant code in UxPlay/lib/raop_rtp_mirror.c

```
            } else if (payload == NULL && ret == -1) {
                if (errno == EAGAIN || errno == EWOULDBLOCK) continue; // Timeouts can happen even if the connection is fine
                logger_log(raop_rtp_mirror->logger, LOGGER_ERR,
                           "raop_rtp_mirror error  in header recv: %d %s", errno, strerror(errno));
                if (errno == ECONNRESET) conn_reset = true;; 
                break;
            }
```

**Comment by ank-007** [comment] 2024-12-05 07:19
I'll add this line and check, may I know what is the timeout set here?

**Comment by fduncanh** [comment] 2024-12-06 12:23
The code is supposed to take care if cases where the connection is bad but recovers.   uxplay sends a ntp time signal request to the client every three seconds to keep the clock in sync by default if it doesn't get a response, it drops the connection a certain number of failed attempts (by defauylt, 5, but adjustable with option -reset n.   new connections are then allowed, but the "frozen screen" is left in place in case the previous client can restablish the connection.

I dont understand your error.   Something similar happened here:  (from "troubleshooting" in the README document)

>>    Some users using dual-band (2.4GHz/5GHz) routers have reported that clients using the 5GHz band (sometimes) "fail to see UxPlay" (i.e., do not get a response to their mDNS queries), but the 2.4GHz band works. Other projects using Bonjour/mDNS have had similar reports; the issue seems to be router-specific, perhaps related to "auto" rather than fixed channel selection (5GHz has many more channels to switch between), or channel width selections; one speculation is that since mDNS uses UDP protocol (where "lost" messages are not resent), a mDNS query might get lost if channel switching occurs during the query.

>>If your router has this problem, a reported "fix" is to (at least on 5GHz) use fixed channel and/or fixed (not dynamic) channel width.

This isn't quite the same as your issue.


* what I don't understand is how   recv has return a value -1, but errno   has the value  0, "no error"    this is not supposed to happen according to documentation (man recv)

>If no messages are available at the socket, the receive calls wait for a message to arrive, unless the socket is nonblocking (see fcntl(2)), in which case the value -1 is returned and errno is set to EAGAIN or EWOULDBLOCK.  The receive calls normally return any data available, up to the requested amount, rather than waiting for receipt of the full amount requested.

>RETURN VALUE
       These calls return the number of bytes received, or -1 if an error occurred.  In the event of an error, errno is set to indicate the error.  errno

"man errno" states that

>  The  value  in  errno is significant only when the return value of the call indicated an error (i.e., -1 from most system calls; -1 or NULL from most library functions); a function that succeeds is allowed to change errno.  The value of errno is never set to zero by any system call or library function.
       For some system calls and library functions (e.g., getpriority(2)), -1 is a valid return on success.  In such cases, a successful return can be distinguished from an error return by setting errno to zero before the call, and then, if the call returns a  status  that ndicates that an error may have occurred, checking to see if errno has a nonzero value.
       errno is defined by the ISO C standard to be a modifiable lvalue of type int, and must not be explicitly declared; errno may be a macro.  errno is thread-local; setting it in one thread does not affect its value in any other thread.
>   Error numbers and names
       Valid error numbers are all positive numbers.  The <errno.h> header file defines symbolic names for each of the possible error numbers that may appear in errno.


maybe you could add some "printf" statements to the code to clarify what is happening? 
I don't know how to reproduce your issue.    is it the iphone or the router which is doing the frequency hopping.
maybe its a router option that can be switched off as mentioned above in the excerpt from the README ?  ("auto" choice in router channel selection)

**Comment by fduncanh** [comment] 2024-12-07 06:39
@ank-007  please post output from uxplay -d    (debug output) showing what is happening before and after your issue occurs.    

also see it fixing the wireless channel used by your router (deselect "auto" channel setting)   solves the issue

**Comment by fduncanh** [comment] 2024-12-07 15:28
@ank-007 

We have now reproduced your error (only on Windows)  by just shutting down wifi on the iOS device will connected.

It seems that the planned  reset behavior that should occur when the network connection is lost is not working properly on windows (works correctly on  linux or macOS)

On Windows we also see the unexpected behavior that recv  (which receive video packets from client) returns an error flag "-1" but does not set the error number "errno".

Since the issue can be reproduced here, it should be able to be fixed.

**Comment by fduncanh** [comment] 2024-12-08 01:33
@ank-007 

your issue turns out to be more complicated.      The issue that the Windows implementation of sockets ("winsock2.h") uses GetLastErrror() instead of errno to signal errors was easily fixed.   

*  But the real issue is in raop_ntp.c  where the timing signals are sent to the client and received back.

On linux it seems that the socket that recv_from(..) uses is non-blocking, and after the wifi is disconnected, it returns an error with errno errorcode EWOULDBLOCK  (EAGAIN) telling the server to try again.    After a certain number of retries (default value 5), the server gives up and disconnects.      On Windows, the socket seem to block and recv_from(..) does not return after the wifi is disconnected. It should be non-blocking and return an error with code WSAEWOULDBLOCK.
Since the return from recv_from()  is not happening in Windows, the 5 retries never get made.

Eventually, after 120 seconds, the video thread in raop_rtp_mirror times out and gives up and that was the error you eventually saw.     But the true error is in recv_from in raop_ntp.c

* **since many windows users use UxPlay, and no-one has previously reported this longstanding bug, you probably have an issue with the setting on your wifi router that allows channel hopping, and turning this feature off will probably fix your issue.**

But the bug you exposed will get fixed ASAP.   Will need to find out how to make the socket unblocking in Windows

**Comment by fduncanh** [comment] 2024-12-08 06:00
FIXED:  (in githut master branch)

The issue was that the timeout (300msec) used for "recv_from" in raop_ntp.c had been incorrectly translated from the linux form (a struct timeval_t) to the Windows (winsock2.h) form (a DWORD) , so that (in Windows) the socket used for ntp UDP communication with the client blocked when the network connection was cut and no data arrived. 

* this broke (on Windows)  the mechanism for closing the connection if the network connection shut down

* The issue in  raop_rtp_mirror.c  ( an unexpected "errno=0") is a cosmetic one (socket error messages in Windows use GetLastError() instead of errno).   That will be fixed next, but UxPlay should now drop the connection  correctly on Windows when the network connection is lost.

* @ank-007 : many people have been using UxPlay on Windows without encountering this bug.   I think you experience it because your wifii router settings allow channel switching, which is breaking your network connection.   If you had disabled channel switching, (set the router to use a fixed channel for your local network)  you would probably never have exposed this bug.

**Comment by fduncanh** [comment] 2024-12-08 16:33
@ank-007 

We would be interested to know whether the fix  helps your problem with channel hopping (which is probably bad for uxplay connections).      the uxplay option

**Closed** 2024-12-08 16:38 UTC
