### ISSUE TITLE
Audio stopped then restart / keep mute until manual reconnection when AirPlay Mirror in iOS 18?

### ISSUE THREAD

**Issue by DYY-Studio** [FDH2/UxPlay#344] opened 2024-09-19 06:11 UTC
Device: **iPad Pro 11-inch 2022 (iPad14,3)**
System: **iPad OS 18.0 (22A3354)**
Environment: **Windows 11 23H2 / MSYS2 MINGW64**
Connection: **1Gbps Ethernet**

Version:  **h265_new 0473ccd**
Options: **-s 2688x1668 -nohold -h265 -fps 60**

Also can be reproduced in H264 mode with options **-s 1920x1080 -nohold -fps 60**

When play video game, open the Album app to play a video or meet other audio content change, the mirror's audio may stop.

This is the debug logging when the audio shutted down
```
raop_rtp video: now = 1726723162.189435, ntp = 1726723162.224876, latency = -0.035440, ts = 60002.641370, 00 00 00 00  h265
raop_rtp audio: now = 1726723162.194751, ntp = 1726723162.280023, latency = -0.085271, rtp_time=1553823309 seqnum = 37803
raop_buffer_handle_resends first_seqnum=37804 last seqnum=37805
raop_rtp got resend request 37804 1
raop_buffer_handle_resends first_seqnum=37804 last seqnum=37805
raop_rtp got resend request 37804 1

raop_rtp type_c 0x56, packetlen = 20
raop_rtp resent audio packet: seqnum=37804
raop_buffer_handle_resends first_seqnum=37804 last seqnum=37805
raop_rtp got resend request 37804 1
raop_rtp video: now = 1726723162.206178, ntp = 1726723162.241549, latency = -0.035371, ts = 60002.658043, 00 00 00 00  h265

raop_rtp type_c 0x56, packetlen = 20
raop_rtp resent audio packet: seqnum=37804
raop_buffer_handle_resends first_seqnum=37804 last seqnum=37806
raop_rtp got resend request 37804 1

raop_rtp type_c 0x56, packetlen = 20
raop_rtp resent audio packet: seqnum=37804

raop_rtp type_c 0x56, packetlen = 20
raop_rtp resent audio packet: seqnum=37804
raop_rtp video: now = 1726723162.222555, ntp = 1726723162.258222, latency = -0.035667, ts = 60002.674716, 00 00 00 00  h265
raop_buffer_handle_resends first_seqnum=37804 last seqnum=37806
raop_rtp got resend request 37804 1
raop_rtp video: now = 1726723162.239228, ntp = 1726723162.274895, latency = -0.035667, ts = 60002.691389, 00 00 00 00  h265
raop_buffer_handle_resends first_seqnum=37804 last seqnum=37806
raop_rtp got resend request 37804 1
```

Then for seconds the logging changes to this
```
raop_rtp type_c 0x56, packetlen = 20
raop_rtp resent audio packet: seqnum=37804
raop_buffer_handle_resends first_seqnum=37804 last seqnum=38210
raop_rtp got resend request 37804 1

raop_rtp type_c 0x56, packetlen = 8
Received empty resent audio packet length 8, seqnum=0:
80 d6 00 01 93 ac 00 00

raop_buffer_handle_resends first_seqnum=37804 last seqnum=38210
raop_rtp got resend request 37804 1
raop_rtp video: now = 1726723167.809956, ntp = 1726723167.843733, latency = -0.033777, ts = 60008.260227, 00 00 00 00  h265

raop_rtp type_c 0x56, packetlen = 8
Received empty resent audio packet length 8, seqnum=0:
80 d6 00 01 93 ac 00 00

raop_buffer_handle_resends first_seqnum=37804 last seqnum=38210
raop_rtp got resend request 37804 1

raop_rtp type_c 0x56, packetlen = 8
Received empty resent audio packet length 8, seqnum=0:
80 d6 00 01 93 ac 00 00

raop_buffer_handle_resends first_seqnum=37804 last seqnum=38211
raop_rtp got resend request 37804 1

raop_rtp type_c 0x56, packetlen = 8
raop_rtp video: now = 1726723167.825252, ntp = 1726723167.860406, latency = -0.035154, ts = 60008.276900, 00 00 00 00  h265
Received empty resent audio packet length 8, seqnum=0:
80 d6 00 01 93 ac 00 00

raop_buffer_handle_resends first_seqnum=37804 last seqnum=38211
raop_rtp got resend request 37804 1

raop_rtp type_c 0x56, packetlen = 8
Received empty resent audio packet length 8, seqnum=0:
80 d6 00 01 93 ac 00 00
```

https://github.com/user-attachments/assets/77b673e5-df87-4292-8b5a-e9c790804767

This video shows one of the stable reproduction. And this time it keeps mute and shows _the second logging_ for almost 2 minutes

**Comment by fduncanh** [comment] 2024-09-19 14:04
@DYY-Studio Thanks for testing

Yes there seem to be some audio issues with h265 mode.   This is still a WIP so it is very useful to get feedback!.
I noticed that initially audio didnt play in h265, then started.       Your debug shows audio resend requests.

The h265 support is very new, and so far main focus has been on getting h265 video working.   The audio needs to be examined to find out what is happening.   have you looked at it after "export GST_DEBUG=2  (or =4)  ?

**Comment by fduncanh** [comment] 2024-09-19 14:25
>Also can be reproduced in H264 mode with options -s 1920x1080 -nohold -fps 60

@DYY-Studio Can you explain this some more?

Does this happen with the regular released (master branch,not h265_new branch) UxPlay?   In that case something has broken in h265_new when running without -h265 option.    (It _should_ behave just like the current master branch UxPlay when the -h265 option is not used).

This should be easier to fix if it is a regression in non-h265 mode.

**Comment by DYY-Studio** [comment] 2024-09-19 15:38
I have also tested my **iPhone SE 3rd (iPhone14,6)** in **iOS 16.2** with master branch, Wi-Fi connection.
It's same as my iPad Pro. Slience.

**Comment by fduncanh** [comment] 2024-09-19 18:46
I have not yet  tested   iOS18/iPadOS 18  .  Will need to see if anything new in iOS18 has broken anything.

But if you see an issue in iOS16.3 it's not that.

can  you list what the test is, in the precise form

1.  do this
2. do this
3.  do this
...
(see the problem)

thanks


If you do NOT use the -s wxh@r   option, (just use -s wxh) what happens?


In particular, on github master AND in h265_new ,   a change in the internal representation of the   refresh rate 60hz
specified as -s 1920x1080@60    was recently made (based on wireshark analysis of AppleTV gen 3) and might be incorrect,

* so please check (1. without -s option   2. with -s 1920x1080  and 3. -s 1920x1080@30   4. -s 1920x1080@60.)

Thanks!

**Comment by fduncanh** [comment] 2024-09-19 18:56
https://github.com/FDH2/UxPlay/commits/88891c01270ab215450dc6ea0a868bb46abb5c66/

better: can you test master BEFORE the change in the refresh rate code was made

**Comment by DYY-Studio** [comment] 2024-09-19 20:13
### iPhone SE 3rd, iOS 16.3, UxPlay 1.69 (0a2dbaa)
Maybe Application specific problem?
Successfully reproduced with _COD MOBILE (CHINA)_, but unstable.
_Link! Like! LoveLive! (JAPAN)_ (Unity Engine) is the App that can most stably reproduce the problem.

options: **-nohold** / NONE

* Open the App
* Close it from background
* Reopen
* **Now mute**
* Exit
* Reopen 
* **Now the audio comes back**

https://github.com/user-attachments/assets/82e4ba6f-abef-496e-9955-5d0a3be2206a

I took a video so you can easily know what I have done.

### iPad Pro 11-inch 2022, iOS 18.0, UxPlay 1.69 (0a2dbaa)

options: NONE

As same as the iPhone SE, _Link! Like! LoveLive!_ can stably reproduce the audio problem.
Other applications seem do not have this problem? or just I haven't tried?

### iPad Pro 11-inch 2022, iOS 18.0, h265_new (0473ccd)

Different from 0a2dbaa, any App can easily reproduce the audio problem.
* Open App
* Exit
* Reopen
* **Now mute**

Tested App: _IDOLY PRIDE (JAPAN)_, _Galaxy on Fire 2_

https://github.com/user-attachments/assets/1b516dc9-27d1-45cf-9b78-e6355f1904b4

**Comment by fduncanh** [comment] 2024-09-28 21:58
@DYY-Studio 
We would like to investigate your  issue.

Can you explain in detail where to get "Link! Like! LoveLive" game.

Is it in App Store ? Something on You Tube?

* Please give an EXACT set of instructions on what is needed to reproduce your issues.  No one here is an expert in these video games.   You need to tell us  exactly what to do.

1 .how to access the game.   (Is it online in a browser, something on YouTube, something that needs to be installed on an iPad/iPhone  from the App Store, etc.)

2. what to do to start the game and see the issue.
thank you.





> As same as the iPhone SE, Link! Like! LoveLive! can stably reproduce the audio problem.
Other applications seem do not have this problem? or just I haven't tried?

**Comment by fduncanh** [comment] 2024-09-28 22:07
OK have found galaxy on fire 2 HD in the Apple app store..  Its currently downloading.

Will it show all your issues, both in h264 on UxPlay-1.69 (master branch) and the experimental h265 version (h265_new branch,  using 4K video with the -h265 option)

**Comment by fduncanh** [comment] 2024-09-28 22:16
Link !Like! Love Live does not seem to be in the App Store  (maybe only in Japan?)

**Comment by fduncanh** [comment] 2024-09-28 23:19
FIXED!

An experimental  change in the audio was accidentally commited.

One this was reverted, audio is working fine, just like in v1.69.

* since Link!Like!Love Live does not seem to be available, can you find some other game which shows an audio problem
in uxplay 1.69, to see if your report can be reproduced in a different app.

Will close this issue as fixed now.

PLEASE REPOST HERE IF YOU THINK IT IS STILL NOT FIXED!

**Closed by fduncanh** 2024-09-28 23:19 UTC
