### ISSUE TITLE
Videoflip got broken in GStreamer 1.22.0   (and was fixed in 1.22.3)   (was: No flip commands working on Raspberry pi 5)

### ISSUE THREAD

**Issue by Boaztheostrich** [FDH2/UxPlay#275] opened 2024-03-10 01:11 UTC
On my rpi 5 running UxPlay version 1.62 I can't get the flip command to work. It seems to just be ignoring the flip command when I am running it.

I tried:

```
uxplay -f H
```
```
uxplay -f V
```
```
uxplay -f I
```

But was unable to get anything to work, I didn't see any error messages related to flipping, although I did get a 
```
gst_v4l2_buffer_pool_orphan: assertion 'bpool' failed
```

I'd be happy to provide more information if needed.

**Comment by fduncanh** [comment] 2024-03-10 08:18
You are correct!

 I checked that nothing in uxplay is broken  (uxplay -d shows the video pipeline, and everything about videoflip is correct.

The issue is that videoflip seesm to have got  broken in GStreamer 1.22.   I verified that it was working on a system with GStreamer 1.20,  but it doesnt work in 1.22

see
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4536

It seems the "videoflip method" used by uxplay is deprecated and  has been superceded by a new "videoflip video-direction property"
which broke the older method.  It's  certainly broken in GStreamer 1.22.0   I assume it is now fixed in some updated release, but that's not much help.  
 
I'll look  into it.

**Comment by fduncanh** [comment] 2024-03-10 08:52
It got fixed in GStreamer-1.22.3 bugfix release.   Unfortunately Raspberry PI OS (Bookworm) has 1.22.0

**Comment by fduncanh** [comment] 2024-03-10 08:57
Here is the fix.   It would be fairly easy to patch GStreamer-1.22.0 with the fix.

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/020fd3d14d74adc6dbf6ea59b684e15030eb1be2

**Comment by Boaztheostrich** [comment] 2024-03-10 15:16
Thanks for the quick response!

What would be my best next steps for patching this? I’m admittedly not the
best at Linux. Is this something I could fix with using nano or another
text editor to just copy paste the values shown in the link you sent?

Or do I need to update streamer or something?

Thank!

**Comment by fduncanh** [comment] 2024-03-10 15:33
I'm looking into it.   I can make you a patch to apply.  I'm also trying to find out how to using the alternative method of setting videoflip mentioned in https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/020fd3d14d74adc6dbf6ea59b684e15030eb1be2

**Comment by Boaztheostrich** [comment] 2024-03-10 15:42
Sounds good thank you! This may be unrelated but is it possible to
dynamically change values like -f H dynamically without shutting down and
restarting the stream?

In my application some apps, such as those using a camera, are best
mirrored to reflect camera movement. While others are best used un flipped
for text readability.

Thanks!
Boaz

**Comment by fduncanh** [comment] 2024-03-10 20:14
Here is the patch:   apply it using exactly the same method  described  [here](https://github.com/FDH2/UxPlay/wiki/Gstreamer-Video4Linux2-plugin-patches) for applying the v4l2 patch  to gstreamer-plugins-good v 1.18.4 in Raspberry Pi OS (Bullseye)  You will be patching libgstvideofilter.so from gstreamer1.0-plugins-good-1.22.0*.deb from Raspberry Pi OS (Bookworm).

The only (obvious) changes are that  
* 1.18.4 is replaced by 1.22.0 
* v4l2_1_18_4_diff3.txt is  replaced by gst_videoflip_1_22_0_diff.txt
* sys/v4l2 is replaced by gst/videofilter
* libgstvideo4linux2.so is replaced by libgstvideofilter.so

The patch is: 

https://github.com/FDH2/UxPlay/files/14551547/gst_videoflip_1_22_0_diff.txt

The problem appeared in GStreamer-1.22.0, was first patched in 1.22.3.   Evidently this did not completely solve all related issues, as versions of an additional patch were applied 3 times, becoming stable in 1.22.6

The patch here includes all these fixes.

**Closed by fduncanh** 2024-03-10 20:14 UTC

**Comment by Boaztheostrich** [comment] 2024-03-10 20:19
Sounds good! I will try this out later today!

Thank you for the help :)

Would it be possible to make changes dynamically while it is running
somehow? Or can run arguments only be applied before the process is
running?

**Comment by fduncanh** [comment] 2024-03-10 20:22
> Would it be possible to make changes dynamically while it is running
somehow? Or can run arguments only be applied before the process is
running?

Uxplay can't change anything after it starts.   Only the client can do that.

**Comment by Boaztheostrich** [comment] 2024-03-10 20:33
Sounds good thank you!

**Comment by fduncanh** [comment] 2024-03-10 21:25
It would certainly be possible to modify uxplay to read some file each time a new connection starts to find out what video orientation to use.
